### ISSUE TITLE
Error : Value cannot be null or whitespace. Parameter name: namespaceName

### ISSUE THREAD

**Issue by YMoukeddar** [Oceanware/XAMLPowerToys2015#1] opened 2016-06-29 10:22 UTC
### Installed product versions
- Visual Studio: 2015
- This extension:1.1.7

### Description
It gives the above error when selecting a viewmodel and hitting Next

that's all it gives.

**Comment by kdawg1406** [comment] 2016-06-29 11:57
YMoukeddar,

Apologies for the trouble you're having.

What is the name of the **NAMESPACE** that you're view model is in?

Can you upload your ViewModel here so I can take a look?

This is a simple issue to resolve and I look forward to solving this for your scenario.

Best,

Karl

**Comment by YMoukeddar** [comment] 2016-06-29 12:01
the Laptop is currently installing an Update, the name of the Namespace is : AgriGestion
the ViewModel is based on Screen, from Stylet, similar to Caliburn.Micro's Screen Base Class

**Comment by kdawg1406** [comment] 2016-06-29 13:08
Can you shared the project or create a small project that has the same features so I can debug and test?

**Comment by YMoukeddar** [comment] 2016-06-29 13:18
Weird, created a new project, used Stylet, created the Viewmodel, launched XPT, and it worked, something must be off with the other project.

**Comment by kdawg1406** [comment] 2016-06-29 13:52
Not sure you can share the solution, if you can, I can debug it.

**Comment by YMoukeddar** [comment] 2016-06-30 12:07
can't share it currently, i'll try to replicate it.

**Comment by kdawg1406** [comment] 2016-07-16 12:29
Closing for now.  Please reopen if you have replicate it in a project you can share.

Thank you,

Karl

**Closed by kdawg1406** 2016-07-16 12:29 UTC

**Comment by tomcrusader** [comment] 2016-10-18 07:32
I've set up a very basic XF project and ran in to the same issue.

Got around it by making a dummy ViewModel and Model with no complexity.

The problem probably occurs because of complex base classes in the ViewModel, I'd stagger a guess that Type Parameters (`<T> where T : class`) isn't supported.

**Comment by kdawg1406** [comment] 2016-10-18 18:31
@tomcrusader do you have an example project that demonstrates the problem on GitHub that I can do the research on?

Thank you,

Karl

**Comment by linuxdoesrock** [comment] 2018-04-23 09:55
I can reproduce the error with the following ViewModel:
```
namespace XamlTest
{
    public class SetValue<T> 
    {
        public T TargetValue { get; set; }
        public T ActualValue { get; set;}
    }


    public class ViewModel
    {
        public decimal Speed { get; set; }
        public SetValue<decimal> Temperature { get; set; }
    }
}
```

If I select the ViewModel class and hit continue I get the error
